### ISSUE TITLE
No peer candidates when running more than 3 nodecore instances

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/nodecore#1]
When I run more than three nodecores on one pc or on more than three pc's within one network (with the same external IP) the fourth nodecore can't connect to a single because there are socket errors and no connection can't be established. See the attached log for more details.

It does not matter in which order I start the nodecores, the first three can find peers and the fourth can't.

[nodecore_output.txt](https://github.com/VeriBlock/nodecore/files/3156729/nodecore_output.txt)

**Comment by timstall** [comment]
0.4.5 should fix this.
https://github.com/VeriBlock/nodecore-releases/releases/download/v0.4.5/nodecore-0.4.5.zip

**Comment by Leonardiae** [comment]
I can confirm this is fixed in 0.4.5.
