### ISSUE TITLE
Make settxfee command foolproof

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/nodecore#118]
Recently I made a mistake setting the fee. I checked nodecore.properties for my currentfee setting which showed: transaction.fee=1000

I wanted to increase it a bit and went to the CLI interface and typed: settxfee 1025
Luckily my transaction was not accepted using this fee :)
When checking nodecore.properties it now shows: transaction.fee=102500000000

According to the documentation I made a mistake and should have set the fee like this: settxfee 0.00001025

May I suggest to improvements to prevent this error from happening again in the future by:
- Showing the fee in nodecore.properties the same way as I'm supposed to set it: 0.00001000 instead of 1000
- When someone sets a fee greater than, say, 1.00000000 show a warning (or maybe in the future create a suggested fee and if one sets it to 100* that suggestion then show a warning)

**Comment by BernatCarbo** [comment]
It should be solved on the next release: https://github.com/VeriBlock/nodecore/commit/0b4c692a2da115990ffa1f318447f21b1acf0d91

**Comment by Leonardiae** [comment]
Great, thanks for the fast action!
