### ISSUE TITLE
Getting Block Information JOSN-RPC

### ISSUE THREAD

**Issue by nxw1990** [VeriBlock/nodecore#12]
Hi:
 I use JSON-RPC to get block information, eg:  curl -X POST http://127.0.0.1:10600/api -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"getinfo","params":{}}' 
.  version is nodecore-0.4.5. But it doesn`t work, What is the reason? Can you give me an example? Thank you!

**Comment by bitspill** [comment]
What do you mean by "doesn't work", are you receiving unexpected results, an error, no response at all?

**Comment by nxw1990** [comment]
I find when  rpc.security.password.enabled=false in nodecore.properties  I can get the right information. but rpc.security.password.enabled = true, nothing output.  if I want set rpc.security.password.enabled is true. How to write use curl? such as when rpc.security.password=123456

**Comment by bitspill** [comment]
If you enable password security, you'll have to add the password to the curl command for it to work.

https://wiki.veriblock.org/index.php?title=NodeCore_HTTP_API#Security

Add `--header "X-VBK-RPC-PASSWORD: 123456"` to your curl command

**Comment by nxw1990** [comment]
> If you enable password security, you'll have to add the password to the curl command for it to work.
> 
> https://wiki.veriblock.org/index.php?title=NodeCore_HTTP_API#Security
> 
> Add `--header "X-VBK-RPC-PASSWORD: 123456"` to your curl command

Thank you very much!

**Comment by BernatCarbo** [comment]
Thanks, we have added the header example at the wiki page.
