### ISSUE TITLE
ESC character in Nodecore output on 

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/nodecore#21]
When running Nodecore in the windows I see several ESC characters, shown as ⍰

Rows are like this: 2019-09-14 11:13:13.087+0200 ⍰[1;37mnc-bus-thread-37⍰[0;39m ⍰[34mINFO ⍰[0;39m ⍰[1;30md

**Comment by BernatCarbo** [comment]
This is related with the console colors which is already solved on the next release.

**Comment by Leonardiae** [comment]
I didn't notice it, but you are right of course. Thanks!
