### ISSUE TITLE
Nodecore-cli.bat too high because lines not set

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/nodecore#3]
Nodecore-cli.bat sets the output window to 90 columns with this command: mode con: cols=90
When I start nodecore-cli the output windows is very high, higher than my desktop, and I always have to resize this window before I can enter a command.

It seems that when you don't set the lines this by default gets the same value as the columns. 

Can you also set the lines, for example to 20? 
MODE CON: COLS=90 LINES=20

Or maybe don't set the columns at all and use the deault settings.

**Comment by BernatCarbo** [comment]
Solved with https://github.com/VeriBlock/nodecore/commit/708638f1196b25d05526de923d46b9740a498d64, thanks!
