### ISSUE TITLE
Example of GetWalletTransactions

### ISSUE THREAD

**Issue by manuelrocha88** [VeriBlock/nodecore#386]
@Leonard requested:

I'm trying to create a curl command for
http://localhost:10600/api/docs#RpcGetTransactionsRequest but can't get it working. 

This does not work:
```
curl -d '{"jsonrpc": "2.0","method": "GetWalletTransactions","params": {requestType:1, "address": "V7bgeLqayERigpvAV6taKctBxE9LCH"},"id": 1}' -H "Content-Type: application/json" -X POST http://localhost:10600/api
```
Which I understand because according to the specs I need to set to Base58-encoded address in bytes, but this does not sound very user-friendly. And when I do this with a c# script using https://github.com/VeriBlock/VeriBlock.Demo.Rpc.Client/blob/master/VeriBlock.Demo.Rpc.Client/Examples.cs then I get results but not related to the address I use. 

So maybe someone can provide an example we can use for third parties/wiki

**Comment by BernatCarbo** [comment]
The command would be 
` curl -d '{"jsonrpc": "2.0","method": "getwallettransactions","params": {requestType:1, "address": "V7bgeLqayERigpvAV6taKctBxE9LCH"},"id": 1}' -H "Content-Type: application/json" -X POST http://localhost:10600/api
`

**Comment by Leonardiae** [comment]
I didnt know it was case sensitive but you are correct, this works. Thanks.
