### ISSUE TITLE
VBK Nodecore Will Not Start on Mac

### ISSUE THREAD

**Issue by ramsey1021** [VeriBlock/nodecore#5]
<img width="1157" alt="Screen Shot 2019-06-18 at 8 28 05 PM" src="https://user-images.githubusercontent.com/51976542/59728357-b627d180-9207-11e9-96d5-50a9d3951b5e.png">

When attempting to run the Nodecore for the first time on a Mac this error pops up. I have already downloaded the correct Java and it allows me to start the wallet, but I cannot run the Nodecore.

**Comment by BernatCarbo** [comment]
Sorry for the late response, at the 0.4.6 with openJDK it should run on a Mac, thank you!
