### ISSUE TITLE
Feature: Add withdrawbitcointoaddress to PoP miner API

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/nodecore#6]
It would be great if the withdrawbitcointoaddress command is available in the PoP miner API and be able to send Bitcoin from the PoP miner to an address using the API.

**Comment by BernatCarbo** [comment]
Thanks, we added this feature for the next release 0.4.7.

**Comment by Leonardiae** [comment]
Great, thanks :)

**Comment by Leonardiae** [comment]
This functionality is released in 0.4.7.
